# My Top 5 PyTorch favorite functions

An short introduction about PyTorch and about the chosen functions. 

- function 1 - TORCH.DEG2RAD
- function 2 - TORCH.DIV
- function 3 - TORCH.NAN_TO_NUM
- function 4 - TORCH.POW
- function 5 - TORCH.ARGMAX

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - TORCH.DEG2RAD

The function converts tensor with degrees into radiants

In [ ]:
deg = torch.tensor([[30, -45], [180, -350.]])
torch.deg2rad(deg)

tensor([[ 0.5236, -0.7854],
        [ 3.1416, -6.1087]])

As you can see 30 degree angle is converted into 0.5235 radians and so on.

In [ ]:
deg2 = torch.tensor([[180, -10], [90, -180], [120, -80]])
torch.deg2rad(deg2)

tensor([[ 3.1416, -0.1745],
        [ 1.5708, -3.1416],
        [ 2.0944, -1.3963]])

here we have give 3 dimential matrix as tensor with angles and it converted all the angles values into radians

In [ ]:
deg3 = torch.tensor([[180, -10], [90, -180], [120]])
torch.deg2rad(deg3)

ValueError: ignored

it can convert only proper shape tensor matrix to radians

Closing comments about when to use this function
* This is really useful function when we want to quickly convert the degrees to radians

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - TORCH.DIV

The function divided all the elements of tensor by give value

In [ ]:
t1 = torch.tensor([[30, -45], [180, -350.]])
torch.div(t1, 10)

tensor([[  3.0000,  -4.5000],
        [ 18.0000, -35.0000]])

As we can see that all the elements of tensor are divided by given (10) value

In [ ]:
t2 = torch.tensor([[180, -10], [90, -180], [120, -80]])
torch.div(t2, 0)

tensor([[inf, -inf],
        [inf, -inf],
        [inf, -inf]])

with 3D tensor matrix, it has divided all the elements with 0 value, without any div by zero error.

In [ ]:
t3 = torch.tensor([[180, -10], [90, -180], [120]])
torch.div(t3, 0)

ValueError: ignored

It needs proper shape tensor to work.

Closing comments about when to use this function
* We can quickly divide all the elements of tensor with given value
* We have to give proper size tensor matrix

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 3 - TORCH.NAN_TO_NUM

It converts nan/poss inf /neg inf values to given number

In [ ]:
import numpy as np
t1 = torch.tensor([[30, -45], [180, np.nan]])
t1

In [ ]:
torch.nan_to_num(t1, 1)

As we can see it has replace nan value with 1

In [ ]:
t2 = torch.tensor([[np.nan, -10], [90, float('inf')], [120, -float('inf')]])
torch.nan_to_num(t2)

As we can see here, it has replace 
* nan -> 0
* inf -> very large number/max datatype number
* -inf -> very small number/min datatype nummber

In [ ]:
t3 = torch.tensor([[np.nan, -10], [90, 'inf'], [120, -float('inf')]])
torch.nan_to_num(t3)

* It does not take str as inf, we have to give float('inf') in tensor matrix

Closing comments about when to use this function
* Very useful function to convert/replace all the nan values with required values in large matrix
* It can be use as imputer (from ML scikit learn)


In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - TORCH.POW

it convert the values from tensor to the power given in the functions

In [ ]:
t1 = torch.tensor([[30, -45], [180, -350.]])
torch.pow(t1, 10)

tensor([[5.9049e+14, 3.4051e+16],
        [3.5705e+22, 2.7585e+25]])

As we can see it has convert each values of tensor into given power in the .pow function

In [ ]:
t2 = torch.tensor([[180, -10], [90, -180], [120, -80]])
torch.pow(t2, 5)

tensor([[ 188956800000,       -100000],
        [   5904900000, -188956800000],
        [  24883200000,   -3276800000]])

it has converted each value in tensor with given power 5

In [ ]:
t3 = torch.tensor([[180, -10], [90, -180], [120,]])
torch.pow(t3, 0.01)

ValueError: ignored

It need proper shape of tensor matrix

Closing comments about when to use this function
* quick way to convert all the elements from tensor to the give power

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - TORCH.ARGMAX

 Return index of max value from all elements from tensor

In [ ]:
t1 = torch.tensor([[30, -45], [180, -350.]])
torch.argmax(t1), torch.max(t1)

(tensor(2), tensor(180.))

As we can see that it has return index of max value and we can conform it with torch.max function

In [ ]:
t2= torch.rand(3, 3)
t2

tensor([[0.5977, 0.7431, 0.7518],
        [0.4048, 0.1597, 0.8834],
        [0.5572, 0.6764, 0.8452]])

In [ ]:
torch.argmax(t2), torch.max(t3)

(tensor(5), tensor(180))

As we can it has return index of max value from the tensor matrix, we can easily verfiy it using torch.max function


In [ ]:
t3 = torch.tensor([[180, -10], [90, -180], [120, 'k']])
torch.argmax(t3)


TypeError: ignored

all the value of tensor must be numbers, string does not work

Closing comments about when to use this function
* very useful function when we want to find index of max value not actualy max value

In [ ]:
jovian.commit(project='01-tensor-operations')

## Conclusion

* 5 functions of pytorch are covered in this book
    function 1 - TORCH.DEG2RAD
    function 2 - TORCH.DIV
    function 3 - TORCH.NAN_TO_NUM
    function 4 - TORCH.POW
    function 5 - TORCH.ARGMAX 
* most error occures with shape of of tensor, we need to keep in mind about propoer matrix shape 
* torch has really amazing documentation
* we can easily search for operation which we want to perform on matrix and we can find possible operations/functions from documentation


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
